package views;

import java.util.Random;
import javax.swing.JTextField;
import logic.Difficulty;
import logic.Equation;
import utils.Util;

/**
 *
 * @author Marci
 */
public class MainForm extends javax.swing.JFrame {

    private SetupForm setupForm;
    private Equation equation;
    private Difficulty difficulty;
    private CorrectAnswerMessage correctAnswerMessage;
    private WrongAnswerMessage wrongAnswerMessage;
    private int hiddenNumber;
    private JTextField hiddenTextField;
    private final static Random random;

    static {
        random = new Random();
    }

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        difficulty = new Difficulty();
        setupEquation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        tfFirstNumber = new javax.swing.JTextField();
        tfOperator = new javax.swing.JTextField();
        tfSecondNumber = new javax.swing.JTextField();
        tfResult = new javax.swing.JTextField();
        tfEqual = new javax.swing.JTextField();
        btCheckAnswer = new javax.swing.JButton();
        btNewExample = new javax.swing.JButton();
        tfAnswer = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSetup = new javax.swing.JMenu();
        miDifficultySetup = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matek gyakorlo");
        setLocationByPlatform(true);
        setResizable(false);

        tfFirstNumber.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfFirstNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFirstNumber.setFocusable(false);

        tfOperator.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfOperator.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfOperator.setFocusable(false);

        tfSecondNumber.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfSecondNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSecondNumber.setFocusable(false);

        tfResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfResult.setFocusable(false);

        tfEqual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfEqual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEqual.setText("=");
        tfEqual.setFocusable(false);

        btCheckAnswer.setText("Ellenorzes");
        btCheckAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckAnswerActionPerformed(evt);
            }
        });

        btNewExample.setText("Uj feladat");
        btNewExample.setEnabled(false);
        btNewExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewExampleActionPerformed(evt);
            }
        });

        tfAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAnswerKeyTyped(evt);
            }
        });

        menuSetup.setText("Beallitasok");

        miDifficultySetup.setText("Nehezsegi szint");
        miDifficultySetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDifficultySetupActionPerformed(evt);
            }
        });
        menuSetup.add(miDifficultySetup);

        jMenuBar1.add(menuSetup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(tfSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(tfEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCheckAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNewExample, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCheckAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNewExample))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDifficultySetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDifficultySetupActionPerformed
        setupForm = new SetupForm(this, difficulty);
        setupForm.setVisible(true);
    }//GEN-LAST:event_miDifficultySetupActionPerformed

    private void btCheckAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckAnswerActionPerformed
        if (tfAnswer.getText().
                length() > 0) {
            int result = getFormattedAnswer();
            if (result == hiddenNumber) {
                setFormAfterCorrectAnswer();
            } else {
                setFormAfterWrongAnswer();
            }
        }
    }//GEN-LAST:event_btCheckAnswerActionPerformed

    private void btNewExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewExampleActionPerformed
        setupEquation();
        btCheckAnswer.setEnabled(true);
        btNewExample.setEnabled(false);
        tfAnswer.setEnabled(true);
        tfAnswer.setText("");
        tfAnswer.requestFocus();
    }//GEN-LAST:event_btNewExampleActionPerformed

    private void tfAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAnswerKeyTyped
        char c = evt.getKeyChar();
        if (!Util.isBetween(c, '0', '9') && c != '\b' && c != '-' || tfAnswer.
                getText().
                length() >= 2) {
            evt.consume();
        }
        if (tfAnswer.getText().
                startsWith("-") && c == '-') {
            evt.consume();
        }
        if (tfAnswer.getText().
                length() > 0) {
            char first = tfAnswer.getText().
                    charAt(0);
            if (Character.isDigit(first) && c == '-') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfAnswerKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCheckAnswer;
    private javax.swing.JButton btNewExample;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuSetup;
    private javax.swing.JMenuItem miDifficultySetup;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfEqual;
    private javax.swing.JTextField tfFirstNumber;
    private javax.swing.JTextField tfOperator;
    private javax.swing.JTextField tfResult;
    private javax.swing.JTextField tfSecondNumber;
    // End of variables declaration//GEN-END:variables

    private void setupEquation() {
        equation = Equation.getRandomEquation();
        fillFormWithEqutation(equation);
        hideRandomField();
    }

    private void fillFormWithEqutation(Equation eq) {
        tfFirstNumber.setText(String.valueOf(eq.getFirstNumber()));
        tfSecondNumber.setText(String.valueOf(eq.getSecondNumber()));
        tfOperator.setText(String.valueOf(eq.getOperator()));
        tfResult.setText(String.valueOf(eq.getResult()));
        tfAnswer.requestFocus();
    }

    private void hideRandomField() {
        String hide = "?";
        int chance = random.nextInt(0, 3);
        switch (chance) {
            case 0:
                tfFirstNumber.setText(hide);
                hiddenNumber = equation.getFirstNumber();
                hiddenTextField = tfFirstNumber;
                break;
            case 1:
                tfSecondNumber.setText(hide);
                hiddenNumber = equation.getSecondNumber();
                hiddenTextField = tfSecondNumber;
                break;
            case 2:
                tfResult.setText(hide);
                hiddenNumber = equation.getResult();
                hiddenTextField = tfResult;
                break;
        }
    }

    private int getFormattedAnswer() {
        String result = tfAnswer.getText();
        result = result.replaceAll("\\s", "");
        int answer = Integer.parseInt(result);
        return answer;
    }

    private void setFormAfterCorrectAnswer() {
        btNewExample.setEnabled(true);
        btCheckAnswer.setEnabled(false);
        tfAnswer.setEnabled(false);
        hiddenTextField.setText(String.valueOf(hiddenNumber));
        correctAnswerMessage = new CorrectAnswerMessage(this, false);
        correctAnswerMessage.setVisible(true);
    }

    private void setFormAfterWrongAnswer() {
        tfAnswer.setText("");
        tfAnswer.requestFocus();
        wrongAnswerMessage = new WrongAnswerMessage(this, false);
        wrongAnswerMessage.setVisible(true);
    }

}
