package views;

import logic.Difficulty;
import utils.Util;

/**
 *
 * @author Marci
 */
public class SetupForm extends javax.swing.JDialog {

    private Difficulty difficulty;

    /**
     * Creates new form SetupForm
     *
     * @param parent
     * @param diff
     */
    public SetupForm(java.awt.Frame parent, Difficulty diff) {
        super(parent, true);
        initComponents();
        this.difficulty = diff;
        tfDifficultyLevel.setText(String.
                valueOf(difficulty.getDifficultyLevel()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btDifficultyDown = new javax.swing.JButton();
        btDifficultyUp = new javax.swing.JButton();
        tfDifficultyLevel = new javax.swing.JTextField();
        btOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Nehezsegi szint:");
        jTextField1.setFocusable(false);

        btDifficultyDown.setText("<<");
        btDifficultyDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDifficultyDownActionPerformed(evt);
            }
        });

        btDifficultyUp.setText(">>");
        btDifficultyUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDifficultyUpActionPerformed(evt);
            }
        });

        tfDifficultyLevel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tfDifficultyLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDifficultyLevel.setFocusable(false);

        btOK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btOK.setText("OK");
        btOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btDifficultyDown, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btOK, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(tfDifficultyLevel))
                        .addGap(18, 18, 18)
                        .addComponent(btDifficultyUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btDifficultyDown))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btDifficultyUp)))
                .addGap(18, 18, 18)
                .addComponent(btOK, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDifficultyUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDifficultyUpActionPerformed
        int newLevel = difficulty.getDifficultyLevel() + 1;
        if (Util.isBetween(newLevel, difficulty.MIN_LEVEL, difficulty.MAX_LEVEL)) {
            difficulty.setDifficultyLevel(newLevel);
            tfDifficultyLevel.setText(String.valueOf(newLevel));
        }
    }//GEN-LAST:event_btDifficultyUpActionPerformed

    private void btDifficultyDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDifficultyDownActionPerformed
        int newLevel = difficulty.getDifficultyLevel() - 1;
        if (Util.isBetween(newLevel, difficulty.MIN_LEVEL, difficulty.MAX_LEVEL)) {
            difficulty.setDifficultyLevel(newLevel);
            tfDifficultyLevel.setText(String.valueOf(newLevel));
        }
    }//GEN-LAST:event_btDifficultyDownActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        dispose();
    }//GEN-LAST:event_btOKActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDifficultyDown;
    private javax.swing.JButton btDifficultyUp;
    private javax.swing.JButton btOK;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfDifficultyLevel;
    // End of variables declaration//GEN-END:variables

}
